### ISSUE TITLE
Find a certificate template

### ISSUE THREAD

**Issue by interrrp** [letsbuilda/shills#4]
Here is @somehybrid's submission:
![image](https://github.com/letsbuilda/shills/assets/111111938/2d96a368-9966-4a49-8092-bd78d44125ed)

**Comment by Anonymous4045** [comment]
Here's one we could use, thoughts?

[linux-shill.pdf](https://github.com/letsbuilda/shills/files/13806345/linux-shill.pdf)

**Comment by interrrp** [comment]
> Here's one we could use, thoughts?
> 
> [linux-shill.pdf](https://github.com/letsbuilda/shills/files/13806345/linux-shill.pdf)

Sure, change the title though, and it's spelled "Shenanigans" with an E

**Comment by Anonymous4045** [comment]
PDFs are a no-go, we need to find/make it in html and later export it.
